{
	"schema_version": "1.6.0",
	"id": "GHSA-mh5c-679w-hh4r",
	"modified": "2020-08-31T18:51:01Z",
	"published": "2020-09-03T21:12:01Z",
	"summary": "Denial of Service in mongodb",
	"details": "Versions of `mongodb` prior to 3.1.13 are vulnerable to Denial of Service. The package fails to properly catch an exception when a collection name is invalid and the DB does not exist, crashing the application.\n\n\n## Recommendation\n\nUpgrade to version 3.1.13 or later.",
	"affected": [
		{
			"package": {
				"ecosystem": "npm",
				"name": "mongodb",
				"purl": "pkg:npm/mongodb"
			},
			"ranges": [
				{
					"type": "SEMVER",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.1.13"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2020/09/GHSA-mh5c-679w-hh4r/GHSA-mh5c-679w-hh4r.json"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://www.npmjs.com/advisories/1203"
		}
	],
	"database_specific": {
		"cwe_ids": [],
		"github_reviewed": true,
		"github_reviewed_at": "2020-08-31T18:51:01Z",
		"nvd_published_at": null,
		"severity": "HIGH"
	}
}
