{
	"schema_version": "1.6.0",
	"id": "MAL-2024-42",
	"modified": "2024-01-06T23:54:23Z",
	"published": "2024-01-06T23:54:23Z",
	"summary": "Malicious code in error-can-not-resolve-resource (npm)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n\n## Source: ossf-package-analysis (c8058f7539047e845eb5aae020f1dbfb03a944fa05d5c90b0221181de3d412e3)\nThe OpenSSF Package Analysis project identified 'error-can-not-resolve-resource' @ 1.0.0 (npm) as malicious.\n\nIt is considered malicious because:\n\n- The package communicates with a domain associated with malicious activity.\n",
	"affected": [
		{
			"package": {
				"ecosystem": "npm",
				"name": "error-can-not-resolve-resource",
				"purl": "pkg:npm/error-can-not-resolve-resource"
			},
			"versions": [
				"1.0.0"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/npm/error-can-not-resolve-resource/MAL-2024-42.json"
			}
		}
	],
	"credits": [
		{
			"name": "OpenSSF: Package Analysis",
			"contact": [
				"https://github.com/ossf/package-analysis",
				"https://openssf.slack.com/channels/package_analysis"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"import_time": "2024-01-07T00:18:37.98156579Z",
				"modified_time": "2024-01-06T23:54:23Z",
				"sha256": "c8058f7539047e845eb5aae020f1dbfb03a944fa05d5c90b0221181de3d412e3",
				"source": "ossf-package-analysis",
				"versions": [
					"1.0.0"
				]
			}
		]
	}
}
